import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sidebar,
  navbar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
  navbar: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-1 max-h-screen bg-pink-200 h-full">
          {sidebar}
          <div className="w-full">
            {navbar}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
